أوفيزي:

  دخول:

    الخدمة: التطبيق

    المنفذ: 8080

خدمات:

  تطبيق:

    يبني: .

    بيئة:

      NODE_ENV: انطلاق

    نشر:

      مصادر:

        حدود:

          الذاكرة: 4000 م

    إعادة التشغيل: دائمًا

    الموانئ:

      - "3000: 3000"

    مميز: صحيح

    يعتمد على:

      - تطبيق

    cap_add:

      - SYS_ADMIN

    إعادة التشغيل: دائمًا

أحجام:

  data:
